version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.1.2
  go: circleci/go@1.7.3
jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: go/default # Use the default executor from the orb
      tag: '1.22.1' # Specify a version tag
    steps:
      - checkout # checkout source code
      - go/load-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - go/test: # Runs 'go test ./...' but includes extensive parameterization for finer tuning.
          covermode: atomic
          failfast: true
          race: true
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/assume_role_with_web_identity:
          region: us-east-1
          role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${AWS_ASSUME_ROLE}
      - aws-cli/setup:
          region: us-east-1
          profile_name: default
      - run:
          name: Install CDK
          command: npm install -g aws-cdk
      - run:
          name: Deploy
          command: cd cdk && cdk deploy --require-approval never
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main
