version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  go: circleci/go@1.11.0
  sonarcloud: sonarsource/sonarcloud@2.0.0
jobs:
  scan:
    docker:
      - image: cimg/node:22.1.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/reports
      - run:
          name: check files
          command: pwd && ls -la
      - sonarcloud/scan
  test:
    executor:
      name: go/default
      tag: 1.22.1
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: create report directory
          command: mkdir -p ~/project/reports
      - run:
          name: install go-junit-report
          command: go install github.com/jstemmer/go-junit-report/v2@latest
      - run:
          name: run go vet
          command: go vet -json ./... > reports/govet-report.out
      - run:
          name: run tests
          command: go test -coverprofile=reports/coverage-report.out -json ./... > reports/test-report.out
      - run:
          name: convert test output to junit
          command: go-junit-report < reports/test-report.out > reports/test-report.xml
      - store_test_results:
          path: ~/project/reports/test-report.xml
      - persist_to_workspace:
          root: ~/project/reports
          paths:
            - govet-report.out
            - test-report.out
            - coverage-report.out
      - run:
          name: check files
          command: pwd && ls -la
  deploy:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/assume_role_with_web_identity:
          region: ${AWS_REGION}
          role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${AWS_ASSUME_ROLE}
      - aws-cli/setup:
          region: ${AWS_REGION}
          profile_name: default
      - run:
          name: install cdk
          command: npm install -g aws-cdk
      - run:
          name: deploy
          command: cd cdk && cdk deploy --require-approval never
workflows:
  test_scan_and_deploy:
    jobs:
      - test
      - scan:
          context:
            - sonarcloud
          requires:
            - test
      - deploy:
          context:
            - aws-cli
          requires:
            - scan