version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.1.2
  go: circleci/go@1.11.0
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/assume_role_with_web_identity:
          region: us-east-1
          role_arn: arn:aws:iam::072340891755:role/CircleCIWorkflow
      - aws-cli/setup:
          region: us-east-1
          profile_name: default
      - go/load-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - go/test: # Runs 'go test ./...' but includes extensive parameterization for finer tuning.
          covermode: atomic
          failfast: true
          race: true
      - persist_to_workspace:
          root: ~/project
          paths: .
      - run: |
          # Constants
          S3_BUCKET=lambda-layers-1684737774331
          S3_KEY="demo-"$(date +%s)".zip"
          LAMBDA_FUNCTION_NAME=demo
          # Upload function.zip
          aws s3 cp build/function.zip s3://$S3_BUCKET/$S3_KEY
          # Update the Lambda function
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY