version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  go: circleci/go@1.11.0
jobs:
  test: # this can be any name you choose
    executor:
      name: go/default # use the default executor from the orb
      tag: '1.22.1' # specify a version tag
    steps:
      - checkout # checkout source code
      - go/load-cache # load cached go modules.
      - go/mod-download # run 'go mod download'.
      - go/save-cache # save go modules to cache.
      - go/test: # runs 'go test ./...' but includes extensive parameterization for finer tuning.
          covermode: atomic
          failfast: true
          race: true
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/assume_role_with_web_identity:
          region: ${AWS_REGION}
          role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${AWS_ASSUME_ROLE}
      - aws-cli/setup:
          region: ${AWS_REGION}
          profile_name: default
      - run:
          name: install cdk
          command: npm install -g aws-cdk
      - run:
          name: deploy
          command: cd cdk && cdk deploy --require-approval never
workflows:
  test_and_deploy: # this can be any name you choose
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
