version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.1.2
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/assume_role_with_web_identity:
          region: us-east-1
          role_arn: arn:aws:iam::072340891755:role/CircleCIWorkflow
      - aws-cli/setup:
          region: us-east-1
          profile_name: default
      - run:
          name: CDK Deploy
          command: cd cdk && cdk deploy